---
# Variables spécifiques aux orderers

orderer_type: "etcdraft"
orderer_batch_timeout: "2s"
orderer_batch_max_message_count: 500
orderer_max_channels: 10

# Règles de pare-feu pour orderers
orderer_ufw_rules:
  - { port: 7050, proto: tcp, rule: allow, comment: 'Orderer Port' }
  - { port: 7053, proto: tcp, rule: allow, comment: 'Orderer Admin Port' }
  - { port: 9443, proto: tcp, rule: allow, comment: 'Orderer Metrics' }
  - { port: 10054, proto: tcp, rule: allow, comment: 'CA Orderer' }

# Variables d'environnement Orderer
orderer_env:
  FABRIC_LOGGING_SPEC: "INFO"
  ORDERER_GENERAL_LISTENADDRESS: "0.0.0.0"
  ORDERER_GENERAL_LISTENPORT: "7050"
  ORDERER_GENERAL_LOCALMSPID: "OrdererMSP"
  ORDERER_GENERAL_LOCALMSPDIR: "/var/hyperledger/orderer/msp"
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_PRIVATEKEY: "/var/hyperledger/orderer/tls/server.key"
  ORDERER_GENERAL_TLS_CERTIFICATE: "/var/hyperledger/orderer/tls/server.crt"
  ORDERER_GENERAL_TLS_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: "/var/hyperledger/orderer/tls/server.crt"
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: "/var/hyperledger/orderer/tls/server.key"
  ORDERER_GENERAL_CLUSTER_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_GENERAL_BOOTSTRAPMETHOD: "none"
  ORDERER_CHANNELPARTICIPATION_ENABLED: "true"
  ORDERER_ADMIN_TLS_ENABLED: "true"
  ORDERER_ADMIN_TLS_CERTIFICATE: "/var/hyperledger/orderer/tls/server.crt"
  ORDERER_ADMIN_TLS_PRIVATEKEY: "/var/hyperledger/orderer/tls/server.key"
  ORDERER_ADMIN_TLS_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_ADMIN_TLS_CLIENTROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_ADMIN_LISTENADDRESS: "0.0.0.0:7053"
  ORDERER_OPERATIONS_LISTENADDRESS: "0.0.0.0:9443"
  ORDERER_METRICS_PROVIDER: "prometheus"
