version: '3.8'

networks:
  foncier:
    name: fabric-ca
    driver: bridge

services:
  
  # ============================================================================
  # CA pour l'organisation AFOR
  # ============================================================================
  ca-afor:
    image: hyperledger/fabric-ca:1.5
    container_name: ca-afor
    labels:
      service: hyperledger-fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-afor
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network/organizations/fabric-ca/afor:/etc/hyperledger/fabric-ca-server
    networks:
      - foncier

  # ============================================================================
  # CA pour l'organisation CVGFR
  # ============================================================================
  ca-cvgfr:
    image: hyperledger/fabric-ca:1.5
    container_name: ca-cvgfr
    labels:
      service: hyperledger-fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cvgfr
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network/organizations/fabric-ca/cvgfr:/etc/hyperledger/fabric-ca-server
    networks:
      - foncier

  # ============================================================================
  # CA pour l'organisation PREFET
  # ============================================================================
  ca-prefet:
    image: hyperledger/fabric-ca:1.5
    container_name: ca-prefet
    labels:
      service: hyperledger-fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-prefet
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network/organizations/fabric-ca/prefet:/etc/hyperledger/fabric-ca-server
    networks:
      - foncier

  # ============================================================================
  # CA pour l'Orderer Organization
  # ============================================================================
  ca-orderer:
    image: hyperledger/fabric-ca:1.5
    container_name: ca-orderer
    labels:
      service: hyperledger-fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network/organizations/fabric-ca/orderer:/etc/hyperledger/fabric-ca-server
    networks:
      - foncier
